### ISSUE TITLE
Wiring up the Arduino with the level shifter

### ISSUE THREAD

**Issue by rayrayrayraydog** [SvOlli/USB2Amiga#1]
Hi,

I'm working to build this adapter for an Amiga 1000 (possibly the first one?).  I'm just having a bit of trouble following how you've wired up the level shifter in your pictures.  Can you help with some higher res photos or more clear docs in the project?

Thanks.

**Comment by rayrayrayraydog** [comment]
Ah, nevermind.  I finally got the keyboard input working with my A1000 today using DB9.ino.

**Comment by SvOlli** [comment]
Dang!

Something seems to be wrong with my email notification, as I just noticed this ticket by accident. Sorry.

Also sorry about the confusion with the level shifters. With my incarnations of this project I tend to not use them anymore. [update] It makes the setup easier to build and takes up less space. [/update]

This is also because the software takes open collector into account: the "1" signal is done by putting the pin into input mode, only for the "0" the ATmega is put into output mode. Having more the 4.3V at an input pin is outside of the specification of the Arduino, but my current setup for the CDTV is now running for about a year without any problems being used regularly, being powered all of the time, since I want to turn the CDTV on via keyboard.

May I quote you on the main page for a successful build of the A1000 variant?

**Comment by rayrayrayraydog** [comment]
Yes you may, but I'm still working on some kinks with the keyboard input.
I was able to get the mouse fully working without the level shifter, but
for the keyboard data pins it seems to be a requirement.  The keyboard
performance is not perfect -- keypresses are occasionally missed and things
go haywire if I start to type too fast.  After consulting with someone with
more experience I guess I need to filter line noise with some pull up (or
down) resistors, but haven't figured it out yet.

**Comment by SvOlli** [comment]
Well than let's postpone the success message until we've got a real success.

For the problem at hand: on my A2000 the adapter works fully without level shifters. Since the software is fully utilizing the open collector achitecture (as mentioned above), the level shifter should not make any difference, as would only (convert down) the '1' signal sent by the Amiga from +5V to +3.3V, but never they other way around.

So if it was my setup, my next move would be a taking off the level shifter for the keyboard as well and replace them with pull-up resistors (pull down should not work, since the ATmega as stated above never pulls up a line, only set them to input for '1'). But I'm no expert on the hardware.

**Comment by rayrayrayraydog** [comment]
Sounds good.  I have a second build mostly complete on a breadboard, I will remove the level shifter and give this a try over the next couple days.  Thanks!

**Comment by rayrayrayraydog** [comment]
Hi again.  I've spent some time experimenting with this today on a breadboard.  I got everything working without the level shifter on the keyboard pins just fine, but the performance seems to be the same as when I did use it.  I then tried pull-up resistors on the KB Data and Sync pins.

I tried several different resistor values, but found that a pull-up value of 1K ohm to 5V gave me the best results.  I still get extra characters here and there (most often numbers ??) but if I type a little slower than my fastest speed I would say things are working well enough most of the time.  There are still occasions where a bunch of characters will be spit out in the middle of typing. 

Showing performance with 1k ohm pull-up to 5v
![screenshot](https://user-images.githubusercontent.com/16981101/117556110-5fae2100-b033-11eb-8518-5c8a746b84ea.jpg)

Actual build in use
![build](https://user-images.githubusercontent.com/16981101/117556109-5f158a80-b033-11eb-98b8-65b473f42dd4.jpg)
